fix: 修复kubepanel打包

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -27,7 +27,7 @@ COPY pnpm-lock.yaml package.json pnpm-workspace.yaml ./
 
 RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
   [ -f pnpm-lock.yaml ] && pnpm fetch || \
-  (echo "Lockfile not found." && exit 1) 
+  (echo "Lockfile not found." && exit 1)
 COPY ./tsconfig.json ./tsconfig.json
 COPY ./tsconfig.deps.json ./tsconfig.deps.json
 COPY ./tsconfig.base.json ./tsconfig.base.json
@@ -36,7 +36,7 @@ COPY ./packages ./packages
 
 RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
 pnpm -r --offline --filter=./packages/* install \
-&& pnpm -r --filter=./packages/* run build 
+&& pnpm -r --filter=./packages/* run build
 
 FROM deps AS builder
 
@@ -87,7 +87,7 @@ USER nextjs
 COPY --from=builder /app/$path/next.config.js ./$path/next.config.js
 RUN if ["$name" = "objectstorage" ]; then \
   COPY --from=builder /app/$path/next-i18next.config.js ./$path/next-i18next.config.js; \
-  fi
+fi
 COPY --from=builder /app/$path/public ./$path/public
 COPY --from=builder --chown=nextjs:nodejs /app/$path/.next/standalone ./
 COPY --from=builder --chown=nextjs:nodejs /app/$path/.next/static ./$path/.next/static
